name: Docker build

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
