name: Build

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tokenlist:
    runs-on: ubuntu-latest
    env:
      SOLANA_NETWORK: ${{ secrets.SOLANA_NETWORK }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
